const LANGUAGES = {
  af: {
    code: 'af',
    name: 'Afrikaans',
    localized_name: 'Afrikaans',
    rtl: false,
  },
  am: {
    code: 'am',
    name: 'Amharic',
    localized_name: 'አማርኛ',
    rtl: false,
  },
  ar: {
    code: 'ar',
    name: 'Arabic',
    localized_name: 'العربية',
    rtl: true,
  },
  as: {
    code: 'as',
    name: 'Assamese',
    localized_name: 'অসমীয়া',
    rtl: false,
  },
  az: {
    code: 'az',
    name: 'Azerbaijani',
    localized_name: 'Azerbaijani',
    rtl: false,
  },
  bal: {
    code: 'bal',
    name: 'Balochi',
    localized_name: 'Balochi',
    rtl: false,
  },
  be: {
    code: 'be',
    name: 'Belarusian',
    localized_name: 'Беларуская',
    rtl: false,
  },
  bg: {
    code: 'bg',
    name: 'Bulgarian',
    localized_name: 'Български',
    rtl: false,
  },
  bn: {
    code: 'bn',
    name: 'Bengali',
    localized_name: 'বাংলা',
    rtl: false,
  },
  bn_IN: {
    code: 'bn_IN',
    name: 'Bengali (India)',
    localized_name: 'বাংলা',
    rtl: false,
  },
  bs: {
    code: 'bs',
    name: 'Bosnian',
    localized_name: 'Bosanski',
    rtl: false,
  },
  ca: {
    code: 'ca',
    name: 'Catalan',
    localized_name:
    'Català',
    rtl: false,
  },
  cs: {
    code: 'cs',
    name: 'Czech',
    localized_name: 'Čeština',
    rtl: false,
  },
  cy: {
    code: 'cy',
    name: 'Welsh',
    localized_name: 'Cymraeg',
    rtl: false,
  },
  da: {
    code: 'da',
    name: 'Danish',
    localized_name: 'Dansk',
    rtl: false,
  },
  de: {
    code: 'de',
    name: 'German',
    localized_name: 'Deutsch',
    rtl: false,
  },
  de_CH: {
    code: 'de_CH',
    name: 'German (Switzerland)',
    localized_name: 'Deutsch (Schweiz)',
    rtl: false,
  },
  dz: {
    code: 'dz',
    name: 'Dzongkha',
    localized_name: 'རྫོང་ཁ',
    rtl: false,
  },
  el: {
    code: 'el',
    name: 'Greek',
    localized_name: 'Ελληνικά',
    rtl: false,
  },
  en: {
    code: 'en',
    name: 'English',
    localized_name: 'English',
    rtl: false,
  },
  en_GB: {
    code: 'en_GB',
    name: 'English (United Kingdom)',
    localized_name: 'English (UK)',
    rtl: false,
  },
  en_ZA: {
    code: 'en_ZA',
    name: 'English (South Africa)',
    localized_name: 'English (South Africa)',
    rtl: false,
  },
  es: {
    code: 'es',
    name: 'Spanish',
    localized_name: 'Español',
    rtl: false,
  },
  et: {
    code: 'et',
    name: 'Estonian',
    localized_name: 'Eesti',
    rtl: false,
  },
  eu: {
    code: 'eu',
    name: 'Basque',
    localized_name: 'Euskara',
    rtl: false,
  },
  fa: {
    code: 'fa',
    name: 'Persian',
    localized_name: 'Persian',
    rtl: true,
  },
  fi: {
    code: 'fi',
    name: 'Finnish',
    localized_name: 'Suomi',
    rtl: false,
  },
  fr: {
    code: 'fr',
    name: 'French',
    localized_name: 'Français',
    rtl: false,
  },
  fur: {
    code: 'fur',
    name: 'Friulian',
    localized_name: 'Friulian',
    rtl: false,
  },
  fy: {
    code: 'fy',
    name: 'Western Frisian',
    localized_name: 'Western Frisian',
    rtl: false,
  },
  ga: {
    code: 'ga',
    name: 'Irish',
    localized_name: 'Gaeilge',
    rtl: false,
  },
  gl: {
    code: 'gl',
    name: 'Galician',
    localized_name: 'Galego',
    rtl: false,
  },
  gu: {
    code: 'gu',
    name: 'Gujarati',
    localized_name: 'ગુજરાતી',
    rtl: false,
  },
  he: {
    code: 'he',
    name: 'Hebrew',
    localized_name: 'עברית',
    rtl: true,
  },
  hi: {
    code: 'hi',
    name: 'Hindi',
    localized_name: 'हिन्दी',
    rtl: false,
  },
  hr: {
    code: 'hr',
    name: 'Croatian',
    localized_name: 'Hrvatski',
    rtl: false,
  },
  ht: {
    code: 'ht',
    name: 'Haitian (Haitian Creole)',
    localized_name: 'Kreyòl ayisyen',
    rtl: false,
  },
  hu: {
    code: 'hu',
    name: 'Hungarian',
    localized_name: 'Magyar',
    rtl: false,
  },
  hy: {
    code: 'hy',
    name: 'Armenian',
    localized_name: 'Հայերեն',
    rtl: false,
  },
  id: {
    code: 'id',
    name: 'Indonesian',
    localized_name: 'Bahasa Indonesia',
    rtl: false,
  },
  ilo: {
    code: 'ilo',
    name: 'Iloko',
    localized_name: 'Iloko',
    rtl: false,
  },
  is: {
    code: 'is',
    name: 'Icelandic',
    localized_name: 'Íslenska',
    rtl: false,
  },
  it: {
    code: 'it',
    name: 'Italian',
    localized_name: 'Italiano',
    rtl: false,
  },
  ja: {
    code: 'ja',
    name: 'Japanese',
    localized_name: '日本語',
    rtl: false,
  },
  ka: {
    code: 'ka',
    name: 'Georgian',
    localized_name: 'ქართული',
    rtl: false,
  },
  kn: {
    code: 'kn',
    name: 'Kannada',
    localized_name: 'ಕನ್ನಡ',
    rtl: false,
  },
  ko: {
    code: 'ko',
    name: 'Korean',
    localized_name: '한국어',
    rtl: false,
  },
  ku: {
    code: 'ku',
    name: 'Kurdish',
    localized_name: 'Kurdî, كوردی‎',
    rtl: true,
  },
  lo: {
    code: 'lo',
    name: 'Lao',
    localized_name: 'ພາສາລາວ',
    rtl: false,
  },
  lt: {
    code: 'lt',
    name: 'Lithuanian',
    localized_name: 'Lietuvių',
    rtl: false,
  },
  lv: {
    code: 'lv',
    name: 'Latvian',
    localized_name: 'Latviešu',
    rtl: false,
  },
  mai: {
    code: 'mai',
    name: 'Maithili',
    localized_name: 'Maithili',
    rtl: false,
  },
  mk: {
    code: 'mk',
    name: 'Macedonian',
    localized_name: 'Македонски',
    rtl: false,
  },
  ml: {
    code: 'ml',
    name: 'Malayalam',
    localized_name: 'മലയാളം',
    rtl: false,
  },
  mn: {
    code: 'mn',
    name: 'Mongolian',
    localized_name: 'монгол',
    rtl: false,
  },
  mr: {
    code: 'mr',
    name: 'Marathi',
    localized_name: 'मराठी',
    rtl: false,
  },
  ms: {
    code: 'ms',
    name: 'Malay',
    localized_name: 'Bahasa Melayu',
    rtl: false,
  },
  mt: {
    code: 'mt',
    name: 'Maltese',
    localized_name: 'Malti',
    rtl: false,
  },
  my: {
    code: 'my',
    name: 'Burmese',
    localized_name: 'Burmese',
    rtl: false,
  },
  nb: {
    code: 'nb',
    name: 'Norwegian Bokmål',
    localized_name: 'Norsk (bokmål)',
    rtl: false,
  },
  ne: {
    code: 'ne',
    name: 'Nepali',
    localized_name: 'नेपाली',
    rtl: false,
  },
  nl: {
    code: 'nl',
    name: 'Dutch',
    localized_name: 'Nederlands',
    rtl: false,
  },
  nn: {
    code: 'nn',
    name: 'Norwegian Nynorsk',
    localized_name: 'Norsk nynorsk',
    rtl: false,
  },
  no: {
    code: 'no',
    name: 'Norwegian',
    localized_name: 'Norsk',
    rtl: false,
  },
  nso: {
    code: 'nso',
    name: 'Northern Sotho',
    localized_name: 'Northern Sotho',
    rtl: false,
  },
  or: {
    code: 'or',
    name: 'Oriya',
    localized_name: 'ଓଡ଼ିଆ',
    rtl: false,
  },
  pa: {
    code: 'pa',
    name: 'Panjabi (Punjabi)',
    localized_name: 'ਪੰਜਾਬੀ‎',
    rtl: false,
  },
  pl: {
    code: 'pl',
    name: 'Polish',
    localized_name: 'Polski',
    rtl: false,
  },
  pt: {
    code: 'pt',
    name: 'Portuguese',
    localized_name: 'Português',
    rtl: false,
  },
  pt_BR: {
    code: 'pt_BR',
    name: 'Portuguese (Brazil)',
    localized_name: 'Português (Brasil)',
    rtl: false,
  },
  ro: {
    code: 'ro',
    name: 'Romanian',
    localized_name: 'Română',
    rtl: false,
  },
  ru: {
    code: 'ru',
    name: 'Russian',
    localized_name: 'Русский',
    rtl: false,
  },
  si: {
    code: 'si',
    name: 'Sinhala',
    localized_name: 'සිංහල',
    rtl: false,
  },
  sk: {
    code: 'sk',
    name: 'Slovak',
    localized_name: 'Slovenčina',
    rtl: false,
  },
  sl: {
    code: 'sl',
    name: 'Slovenian',
    localized_name: 'Slovenščina',
    rtl: false,
  },
  sq: {
    code: 'sq',
    name: 'Albanian',
    localized_name: 'Shqipe',
    rtl: false,
  },
  sr: {
    code: 'sr',
    name: 'Serbian',
    localized_name: 'Српски',
    rtl: false,
  },
  'sr@latin': {
    code: 'sr@latin',
    name: 'Serbian (Latin)',
    localized_name: 'Српски',
    rtl: false,
  },
  st: {
    code: 'st',
    name: 'Sotho, Southern',
    localized_name: 'Sesotho',
    rtl: false,
  },
  sv: {
    code: 'sv',
    name: 'Swedish',
    localized_name: 'Svenska',
    rtl: false,
  },
  ta: {
    code: 'ta',
    name: 'Tamil',
    localized_name: 'தமிழ்',
    rtl: false,
  },
  te: {
    code: 'te',
    name: 'Telugu',
    localized_name: 'తెలుగు',
    rtl: false,
  },
  tg: {
    code: 'tg',
    name: 'Tajik',
    localized_name: 'тоҷикӣ, toğikī, تاجیکی‎',
    rtl: false,
  },
  th: {
    code: 'th',
    name: 'Thai',
    localized_name: 'ภาษาไทย',
    rtl: false,
  },
  tl: {
    code: 'tl',
    name: 'Tagalog',
    localized_name: 'Tagalog',
    rtl: false,
  },
  tr: {
    code: 'tr',
    name: 'Turkish',
    localized_name: 'Türkçe',
    rtl: false,
  },
  ur: {
    code: 'ur',
    name: 'Urdu',
    localized_name: 'اردو',
    rtl: true,
  },
  uk: {
    code: 'uk',
    name: 'Ukrainian',
    localized_name: 'Українська',
    rtl: false,
  },
  vi: {
    code: 'vi',
    name: 'Vietnamese',
    localized_name: 'Tiếng Việt',
    rtl: false,
  },
  wo: {
    code: 'wo',
    name: 'Wolof',
    localized_name: 'Wollof',
    rtl: false,
  },
  zh_CN: {
    code: 'zh_CN',
    name: 'Chinese (China)',
    localized_name: '中文 (中国)',
    rtl: false,
  },
  zh_HK: {
    code: 'zh_HK',
    name: 'Chinese (Hong Kong)',
    localized_name: '中文 (香港)',
    rtl: false,
  },
  zh_TW: {
    code: 'zh_TW',
    name: 'Chinese (Taiwan)',
    localized_name: '中文 (台灣)',
    rtl: false,
  },
  zu: {
    code: 'zu',
    name: 'Zulu',
    localized_name: 'isiZulu',
    rtl: false,
  },
  es_AR: {
    code: 'es_AR',
    name: 'Spanish (Argentina)',
    localized_name: 'Español (Argentina)',
    rtl: false,
  },
  bo: {
    code: 'bo',
    name: 'Tibetan',
    localized_name: 'Tibetan',
    rtl: false,
  },
  ast: {
    code: 'ast',
    name: 'Asturian',
    localized_name: 'Asturian',
    rtl: false,
  },
  en_US: {
    code: 'en_US',
    name: 'English (United States)',
    localized_name: 'English (US)',
    rtl: false,
  },
  eo: {
    code: 'eo',
    name: 'Esperanto',
    localized_name: 'Esperanto',
    rtl: false,
  },
  ks: {
    code: 'ks',
    name: 'Kashmiri',
    localized_name: 'Kashmiri',
    rtl: false,
  },
  ky: {
    code: 'ky',
    name: 'Kyrgyz',
    localized_name: 'Kyrgyz',
    rtl: false,
  },
  la: {
    code: 'la',
    name: 'Latin',
    localized_name: 'Latin',
    rtl: false,
  },
  xh: {
    code: 'xh',
    name: 'Xhosa',
    localized_name: 'Xhosa',
    rtl: false,
  },
  es_MX: {
    code: 'es_MX',
    name: 'Spanish (Mexico)',
    localized_name: 'Español (Mexico)',
    rtl: false,
  },
  km: {
    code: 'km',
    name: 'Khmer',
    localized_name: 'Khmer',
    rtl: false,
  },
  fo: {
    code: 'fo',
    name: 'Faroese',
    localized_name: 'Faroese',
    rtl: false,
  },
  kk: {
    code: 'kk',
    name: 'Kazakh',
    localized_name: 'Kazakh',
    rtl: false,
  },
  fr_CA: {
    code: 'fr_CA',
    name: 'French (Canada)',
    localized_name: 'Français (Canada)',
    rtl: false,
  },
  nl_BE: {
    code: 'nl_BE',
    name: 'Dutch (Belgium)',
    localized_name: 'Nederlands (België)',
    rtl: false,
  },
  wa: {
    code: 'wa',
    name: 'Walloon',
    localized_name: 'Walloon',
    rtl: false,
  },
  en_AU: {
    code: 'en_AU',
    name: 'English (Australia)',
    localized_name: 'English (Australia)',
    rtl: false,
  },
  'ca@valencia': {
    code: 'ca@valencia',
    name: 'Catalan (Valencian)',
    localized_name: 'Català',
    rtl: false,
  },
  es_ES: {
    code: 'es_ES',
    name: 'Spanish (Spain)',
    localized_name: 'Español',
    rtl: false,
  },
  bn_BD: {
    code: 'bn_BD',
    name: 'Bengali (Bangladesh)',
    localized_name: 'বাংলা',
    rtl: false,
  },
  sw: {
    code: 'sw',
    name: 'Swahili',
    localized_name: 'Kiswahili',
    rtl: false,
  },
  tk: {
    code: 'tk',
    name: 'Turkmen',
    localized_name: 'Turkmen',
    rtl: false,
  },
  uz: {
    code: 'uz',
    name: 'Uzbek',
    localized_name: 'Uzbek',
    rtl: false,
  },
  sco: {
    code: 'sco',
    name: 'Scots',
    localized_name: 'Scots',
    rtl: false,
  },
  lb: {
    code: 'lb',
    name: 'Luxembourgish',
    localized_name: 'Luxembourgish',
    rtl: false,
  },
  ln: {
    code: 'ln',
    name: 'Lingala',
    localized_name: 'Lingala',
    rtl: false,
  },
  tt: {
    code: 'tt',
    name: 'Tatar',
    localized_name: 'Tatar',
    rtl: false,
  },
  fil: {
    code: 'fil',
    name: 'Filipino',
    localized_name: 'Filipino',
    rtl: false,
  },
  gun: {
    code: 'gun',
    name: 'Gun',
    localized_name: 'Gun',
    rtl: false,
  },
  pms: {
    code: 'pms',
    name: 'Piemontese',
    localized_name: 'Piemontese',
    rtl: false,
  },
  arn: {
    code: 'arn',
    name: 'Mapudungun',
    localized_name: 'Mapudungun',
    rtl: false,
  },
  rm: {
    code: 'rm',
    name: 'Romansh',
    localized_name: 'Romansh',
    rtl: false,
  },
  jv: {
    code: 'jv',
    name: 'Javanese',
    localized_name: 'Javanese',
    rtl: false,
  },
  oc: {
    code: 'oc',
    name: 'Occitan (post 1500)',
    localized_name: 'Occitan (post 1500)',
    rtl: false,
  },
  ps: {
    code: 'ps',
    name: 'Pushto',
    localized_name: 'Pushto',
    rtl: true,
  },
  ha: {
    code: 'ha',
    name: 'Hausa',
    localized_name: 'Hausa',
    rtl: false,
  },
  mg: {
    code: 'mg',
    name: 'Malagasy',
    localized_name: 'Malagasy',
    rtl: false,
  },
  mi: {
    code: 'mi',
    name: 'Maori',
    localized_name: 'Maori',
    rtl: false,
  },
  ug: {
    code: 'ug',
    name: 'Uighur',
    localized_name: 'Uighur',
    rtl: false,
  },
  ak: {
    code: 'ak',
    name: 'Akan',
    localized_name: 'Akan',
    rtl: false,
  },
  an: {
    code: 'an',
    name: 'Aragonese',
    localized_name: 'Aragonese',
    rtl: false,
  },
  su: {
    code: 'su',
    name: 'Sundanese',
    localized_name: 'Sundanese',
    rtl: false,
  },
  pap: {
    code: 'pap',
    name: 'Papiamento',
    localized_name: 'Papiamento',
    rtl: false,
  },
  nah: {
    code: 'nah',
    name: 'Nahuatl',
    localized_name: 'Nahuatl',
    rtl: false,
  },
  csb: {
    code: 'csb',
    name: 'Kashubian',
    localized_name: 'Kashubian',
    rtl: false,
  },
  nap: {
    code: 'nap',
    name: 'Neapolitan',
    localized_name: 'Neapolitan',
    rtl: false,
  },
  kw: {
    code: 'kw',
    name: 'Cornish',
    localized_name: 'Cornish',
    rtl: false,
  },
  ve: {
    code: 've',
    name: 'Venda',
    localized_name: 'Venda',
    rtl: false,
  },
  son: {
    code: 'son',
    name: 'Songhay',
    localized_name: 'Songhay',
    rtl: false,
  },
  en_CA: {
    code: 'en_CA',
    name: 'English (Canada)',
    localized_name: 'English (Canada)',
    rtl: false,
  },
  rw: {
    code: 'rw',
    name: 'Kinyarwanda',
    localized_name: 'Kinyarwanda',
    rtl: false,
  },
  crh: {
    code: 'crh',
    name: 'Crimean Turkish',
    localized_name: 'Crimean Turkish',
    rtl: false,
  },
  li: {
    code: 'li',
    name: 'Limburgian',
    localized_name: 'Limburgian',
    rtl: false,
  },
  es_VE: {
    code: 'es_VE',
    name: 'Spanish (Venezuela)',
    localized_name: 'Español (Venezuela)',
    rtl: false,
  },
  frp: {
    code: 'frp',
    name: 'Franco-Provençal (Arpitan)',
    localized_name: 'Franco-Provençal (Arpitan)',
    rtl: false,
  },
  yi: {
    code: 'yi',
    name: 'Yiddish',
    localized_name: 'Yiddish',
    rtl: false,
  },
  fr_FR: {
    code: 'fr_FR',
    name: 'French (France)',
    localized_name: 'Français',
    rtl: false,
  },
  de_DE: {
    code: 'de_DE',
    name: 'German (Germany)',
    localized_name: 'Deutsch',
    rtl: false,
  },
  yo: {
    code: 'yo',
    name: 'Yoruba',
    localized_name: 'Yoruba',
    rtl: false,
  },
  ig: {
    code: 'ig',
    name: 'Igbo',
    localized_name: 'Igbo',
    rtl: false,
  },
  es_PR: {
    code: 'es_PR',
    name: 'Spanish (Puerto Rico)',
    localized_name: 'Español (Puerto Rico)',
    rtl: false,
  },
  nds: {
    code: 'nds',
    name: 'Low German',
    localized_name: 'Low German',
    rtl: false,
  },
  nr: {
    code: 'nr',
    name: 'Ndebele, South',
    localized_name: 'Ndebele, South',
    rtl: false,
  },
  gd: {
    code: 'gd',
    name: 'Gaelic, Scottish',
    localized_name: 'Gaelic, Scottish',
    rtl: false,
  },
  es_CL: {
    code: 'es_CL',
    name: 'Spanish (Chile)',
    localized_name: 'Español (Chile)',
    rtl: false,
  },
  en_IE: {
    code: 'en_IE',
    name: 'English (Ireland)',
    localized_name: 'English (Ireland)',
    rtl: false,
  },
  ta_LK: {
    code: 'ta_LK',
    name: 'Tamil (Sri-Lanka)',
    localized_name: 'தமிழ்',
    rtl: false,
  },
  se: {
    code: 'se',
    name: 'Northern Sami',
    localized_name: 'Northern Sami',
    rtl: false,
  },
  hsb: {
    code: 'hsb',
    name: 'Upper Sorbian',
    localized_name: 'Upper Sorbian',
    rtl: false,
  },
  hne: {
    code: 'hne',
    name: 'Chhattisgarhi',
    localized_name: 'Chhattisgarhi',
    rtl: false,
  },
  ia: {
    code: 'ia',
    name: 'Interlingua',
    localized_name: 'Interlingua',
    rtl: false,
  },
  sc: {
    code: 'sc',
    name: 'Sardinian',
    localized_name: 'Sardinian',
    rtl: false,
  },
  es_CO: {
    code: 'es_CO',
    name: 'Spanish (Colombia)',
    localized_name: 'Español (Colombia)',
    rtl: false,
  },
  es_DO: {
    code: 'es_DO',
    name: 'Spanish (Dominican Republic)',
    localized_name: 'Español (República Dominicana)',
    rtl: false,
  },
  es_PY: {
    code: 'es_PY',
    name: 'Spanish (Paraguay)',
    localized_name: 'Español (Paraguay)',
    rtl: false,
  },
  es_CR: {
    code: 'es_CR',
    name: 'Spanish (Costa Rica)',
    localized_name: 'Español (Costa Rica)',
    rtl: false,
  },
  es_NI: {
    code: 'es_NI',
    name: 'Spanish (Nicaragua)',
    localized_name: 'Español (Nicaragua)',
    rtl: false,
  },
  es_EC: {
    code: 'es_EC',
    name: 'Spanish (Ecuador)',
    localized_name: 'Español (Ecuador)',
    rtl: false,
  },
  es_PE: {
    code: 'es_PE',
    name: 'Spanish (Peru)',
    localized_name: 'Español (Perú)',
    rtl: false,
  },
  es_UY: {
    code: 'es_UY',
    name: 'Spanish (Uruguay)',
    localized_name: 'Español (Uruguay)',
    rtl: false,
  },
  es_BO: {
    code: 'es_BO',
    name: 'Spanish (Bolivia)',
    localized_name: 'Español (Bolivia)',
    rtl: false,
  },
  es_PA: {
    code: 'es_PA',
    name: 'Spanish (Panama)',
    localized_name: 'Español (Panamá)',
    rtl: false,
  },
  es_SV: {
    code: 'es_SV',
    name: 'Spanish (El Salvador)',
    localized_name: 'Español (El Salvador)',
    rtl: false,
  },
  ru_RU: {
    code: 'ru_RU',
    name: 'Russian (Russia)',
    localized_name: 'Русский',
    rtl: false,
  },
  ca_ES: {
    code: 'ca_ES',
    name: 'Catalan (Spain)',
    localized_name: 'Català',
    rtl: false,
  },
  it_IT: {
    code: 'it_IT',
    name: 'Italian (Italy)',
    localized_name: 'Italiano',
    rtl: false,
  },
  uk_UA: {
    code: 'uk_UA',
    name: 'Ukrainian (Ukraine)',
    localized_name: 'Українська',
    rtl: false,
  },
  hu_HU: {
    code: 'hu_HU',
    name: 'Hungarian (Hungary)',
    localized_name: 'Magyar',
    rtl: false,
  },
  ti: {
    code: 'ti',
    name: 'Tigrinya',
    localized_name: 'Tigrinya',
    rtl: false,
  },
  br: {
    code: 'br',
    name: 'Breton',
    localized_name: 'Breton',
    rtl: false,
  },
  so: {
    code: 'so',
    name: 'Somali',
    localized_name: 'Somali',
    rtl: false,
  },
  af_ZA: {
    code: 'af_ZA',
    name: 'Afrikaans (South Africa)',
    localized_name: 'Afrikaans (South Africa)',
    rtl: false,
  },
  sq_AL: {
    code: 'sq_AL',
    name: 'Albanian (Albania)',
    localized_name: 'Shqipe',
    rtl: false,
  },
  am_ET: {
    code: 'am_ET',
    name: 'Amharic (Ethiopia)',
    localized_name: 'አማርኛ',
    rtl: false,
  },
  ar_SA: {
    code: 'ar_SA',
    name: 'Arabic (Saudi Arabia)',
    localized_name: 'العربية (السعودية)',
    rtl: true,
  },
  hy_AM: {
    code: 'hy_AM',
    name: 'Armenian (Armenia)',
    localized_name: 'Հայերեն',
    rtl: false,
  },
  as_IN: {
    code: 'as_IN',
    name: 'Assamese (India)',
    localized_name: 'অসমীয়া',
    rtl: false,
  },
  az_AZ: {
    code: 'az_AZ',
    name: 'Azerbaijani (Azerbaijan)',
    localized_name: 'Azerbaijani (Azerbaijan)',
    rtl: false,
  },
  eu_ES: {
    code: 'eu_ES',
    name: 'Basque (Spain)',
    localized_name: 'Euskara',
    rtl: false,
  },
  be_BY: {
    code: 'be_BY',
    name: 'Belarusian (Belarus)',
    localized_name: 'Беларуская',
    rtl: false,
  },
  bs_BA: {
    code: 'bs_BA',
    name: 'Bosnian (Bosnia and Herzegovina)',
    localized_name: 'Bosanski',
    rtl: false,
  },
  bg_BG: {
    code: 'bg_BG',
    name: 'Bulgarian (Bulgaria)',
    localized_name: 'Български',
    rtl: false,
  },
  my_MM: {
    code: 'my_MM',
    name: 'Burmese (Myanmar)',
    localized_name: 'Burmese (Myanmar)',
    rtl: false,
  },
  hr_HR: {
    code: 'hr_HR',
    name: 'Croatian (Croatia)',
    localized_name: 'Hrvatski',
    rtl: false,
  },
  cs_CZ: {
    code: 'cs_CZ',
    name: 'Czech (Czech Republic)',
    localized_name: 'Čeština',
    rtl: false,
  },
  da_DK: {
    code: 'da_DK',
    name: 'Danish (Denmark)',
    localized_name: 'Dansk',
    rtl: false,
  },
  nl_NL: {
    code: 'nl_NL',
    name: 'Dutch (Netherlands)',
    localized_name: 'Nederlands',
    rtl: false,
  },
  dz_BT: {
    code: 'dz_BT',
    name: 'Dzongkha (Bhutan)',
    localized_name: 'རྫོང་ཁ',
    rtl: false,
  },
  et_EE: {
    code: 'et_EE',
    name: 'Estonian (Estonia)',
    localized_name: 'Eesti',
    rtl: false,
  },
  fo_FO: {
    code: 'fo_FO',
    name: 'Faroese (Faroe Islands)',
    localized_name: 'Faroese (Faroe Islands)',
    rtl: false,
  },
  fi_FI: {
    code: 'fi_FI',
    name: 'Finnish (Finland)',
    localized_name: 'Suomi',
    rtl: false,
  },
  gl_ES: {
    code: 'gl_ES',
    name: 'Galician (Spain)',
    localized_name: 'Galego',
    rtl: false,
  },
  ka_GE: {
    code: 'ka_GE',
    name: 'Georgian (Georgia)',
    localized_name: 'ქართული',
    rtl: false,
  },
  el_GR: {
    code: 'el_GR',
    name: 'Greek (Greece)',
    localized_name: 'Ελληνικά',
    rtl: false,
  },
  gu_IN: {
    code: 'gu_IN',
    name: 'Gujarati (India)',
    localized_name: 'ગુજરાતી',
    rtl: false,
  },
  ht_HT: {
    code: 'ht_HT',
    name: 'Haitian (Haitian Creole) (Haiti)',
    localized_name: 'Kreyòl ayisyen',
    rtl: false,
  },
  he_IL: {
    code: 'he_IL',
    name: 'Hebrew (Israel)',
    localized_name: 'עברית',
    rtl: true,
  },
  hi_IN: {
    code: 'hi_IN',
    name: 'Hindi (India)',
    localized_name: 'हिन्दी',
    rtl: false,
  },
  is_IS: {
    code: 'is_IS',
    name: 'Icelandic (Iceland)',
    localized_name: 'Íslenska',
    rtl: false,
  },
  id_ID: {
    code: 'id_ID',
    name: 'Indonesian (Indonesia)',
    localized_name: 'Indonesian (Indonesia)',
    rtl: false,
  },
  ga_IE: {
    code: 'ga_IE',
    name: 'Irish (Ireland)',
    localized_name: 'Gaeilge',
    rtl: false,
  },
  ja_JP: {
    code: 'ja_JP',
    name: 'Japanese (Japan)',
    localized_name: '日本語',
    rtl: false,
  },
  kn_IN: {
    code: 'kn_IN',
    name: 'Kannada (India)',
    localized_name: 'ಕನ್ನಡ',
    rtl: false,
  },
  ks_IN: {
    code: 'ks_IN',
    name: 'Kashmiri (India)',
    localized_name: 'Kashmiri (India)',
    rtl: false,
  },
  km_KH: {
    code: 'km_KH',
    name: 'Khmer (Cambodia)',
    localized_name: 'Khmer (Cambodia)',
    rtl: false,
  },
  ko_KR: {
    code: 'ko_KR',
    name: 'Korean (Korea)',
    localized_name: '한국어',
    rtl: false,
  },
  ku_IQ: {
    code: 'ku_IQ',
    name: 'Kurdish (Iraq)',
    localized_name: 'Kurdî, كوردی‎',
    rtl: false,
  },
  lo_LA: {
    code: 'lo_LA',
    name: 'Lao (Laos)',
    localized_name: 'ພາສາລາວ',
    rtl: false,
  },
  lv_LV: {
    code: 'lv_LV',
    name: 'Latvian (Latvia)',
    localized_name: 'Latviešu',
    rtl: false,
  },
  lt_LT: {
    code: 'lt_LT',
    name: 'Lithuanian (Lithuania)',
    localized_name: 'Lietuvių',
    rtl: false,
  },
  mk_MK: {
    code: 'mk_MK',
    name: 'Macedonian (Macedonia)',
    localized_name: 'Македонски',
    rtl: false,
  },
  ms_MY: {
    code: 'ms_MY',
    name: 'Malay (Malaysia)',
    localized_name: 'Bahasa Melayu',
    rtl: false,
  },
  ml_IN: {
    code: 'ml_IN',
    name: 'Malayalam (India)',
    localized_name: 'മലയാളം',
    rtl: false,
  },
  mt_MT: {
    code: 'mt_MT',
    name: 'Maltese (Malta)',
    localized_name: 'Malti',
    rtl: false,
  },
  mr_IN: {
    code: 'mr_IN',
    name: 'Marathi (India)',
    localized_name: 'मराठी',
    rtl: false,
  },
  mn_MN: {
    code: 'mn_MN',
    name: 'Mongolian (Mongolia)',
    localized_name: 'монгол',
    rtl: false,
  },
  ne_NP: {
    code: 'ne_NP',
    name: 'Nepali (Nepal)',
    localized_name: 'नेपाली',
    rtl: false,
  },
  no_NO: {
    code: 'no_NO',
    name: 'Norwegian (Norway)',
    localized_name: 'Norsk',
    rtl: false,
  },
  nb_NO: {
    code: 'nb_NO',
    name: 'Norwegian Bokmål (Norway)',
    localized_name: 'Norsk (bokmål)',
    rtl: false,
  },
  nn_NO: {
    code: 'nn_NO',
    name: 'Norwegian Nynorsk (Norway)',
    localized_name: 'Norsk nynorsk',
    rtl: false,
  },
  or_IN: {
    code: 'or_IN',
    name: 'Oriya (India)',
    localized_name: 'ଓଡ଼ିଆ',
    rtl: false,
  },
  pa_IN: {
    code: 'pa_IN',
    name: 'Panjabi (Punjabi) (India)',
    localized_name: 'ਪੰਜਾਬੀ',
    rtl: false,
  },
  fa_IR: {
    code: 'fa_IR',
    name: 'Persian (Iran)',
    localized_name: 'Persian (Iran)',
    rtl: true,
  },
  pl_PL: {
    code: 'pl_PL',
    name: 'Polish (Poland)',
    localized_name: 'Polski',
    rtl: false,
  },
  pt_PT: {
    code: 'pt_PT',
    name: 'Portuguese (Portugal)',
    localized_name: 'Português',
    rtl: false,
  },
  ro_RO: {
    code: 'ro_RO',
    name: 'Romanian (Romania)',
    localized_name: 'Română',
    rtl: false,
  },
  sr_RS: {
    code: 'sr_RS',
    name: 'Serbian (Serbia)',
    localized_name: 'Српски',
    rtl: false,
  },
  si_LK: {
    code: 'si_LK',
    name: 'Sinhala (Sri Lanka)',
    localized_name: 'සිංහල',
    rtl: false,
  },
  sk_SK: {
    code: 'sk_SK',
    name: 'Slovak (Slovakia)',
    localized_name: 'Slovenčina',
    rtl: false,
  },
  sl_SI: {
    code: 'sl_SI',
    name: 'Slovenian (Slovenia)',
    localized_name: 'Slovenščina',
    rtl: false,
  },
  st_ZA: {
    code: 'st_ZA',
    name: 'Sotho, Southern (South Africa)',
    localized_name: 'Sesotho',
    rtl: false,
  },
  sv_SE: {
    code: 'sv_SE',
    name: 'Swedish (Sweden)',
    localized_name: 'Svenska',
    rtl: false,
  },
  tl_PH: {
    code: 'tl_PH',
    name: 'Tagalog (Philippines)',
    localized_name: 'Filipino',
    rtl: false,
  },
  tg_TJ: {
    code: 'tg_TJ',
    name: 'Tajik (Tajikistan)',
    localized_name: 'тоҷикӣ, toğikī, تاجیکی‎',
    rtl: false,
  },
  ta_IN: {
    code: 'ta_IN',
    name: 'Tamil (India)',
    localized_name: 'தமிழ்',
    rtl: false,
  },
  te_IN: {
    code: 'te_IN',
    name: 'Telugu (India)',
    localized_name: 'తెలుగు',
    rtl: false,
  },
  th_TH: {
    code: 'th_TH',
    name: 'Thai (Thailand)',
    localized_name: 'ภาษาไทย',
    rtl: false,
  },
  bo_CN: {
    code: 'bo_CN',
    name: 'Tibetan (China)',
    localized_name: 'Tibetan (China)',
    rtl: false,
  },
  tr_TR: {
    code: 'tr_TR',
    name: 'Turkish (Turkey)',
    localized_name: 'Türkçe',
    rtl: false,
  },
  ur_PK: {
    code: 'ur_PK',
    name: 'Urdu (Pakistan)',
    localized_name: 'اردو',
    rtl: true,
  },
  vi_VN: {
    code: 'vi_VN',
    name: 'Vietnamese (Viet Nam)',
    localized_name: 'Tiếng Việt',
    rtl: false,
  },
  cy_GB: {
    code: 'cy_GB',
    name: 'Welsh (United Kingdom)',
    localized_name: 'Cymraeg',
    rtl: false,
  },
  fy_NL: {
    code: 'fy_NL',
    name: 'Western Frisian (Netherlands)',
    localized_name: 'Western Frisian (Netherlands)',
    rtl: false,
  },
  wo_SN: {
    code: 'wo_SN',
    name: 'Wolof (Senegal)',
    localized_name: 'Wollof',
    rtl: false,
  },
  zu_ZA: {
    code: 'zu_ZA',
    name: 'Zulu (South Africa)',
    localized_name: 'isiZulu',
    rtl: false,
  },
  'be@tarask': {
    code: 'be@tarask',
    name: 'Belarusian (Tarask)',
    localized_name: 'Беларуская (Tarask)',
    rtl: false,
  },
  'sr_RS@latin': {
    code: 'sr_RS@latin',
    name: 'Serbian (Latin) (Serbia)',
    localized_name: 'Српски',
    rtl: false,
  },
  zh: {
    code: 'zh',
    name: 'Chinese',
    localized_name: '中文',
    rtl: false,
  },
  to: {
    code: 'to',
    name: 'Tongan',
    localized_name: 'Tongan',
    rtl: false,
  },
  sm: {
    code: 'sm',
    name: 'Samoan',
    localized_name: 'Samoan',
    rtl: false,
  },
  vls: {
    code: 'vls',
    name: 'Vlaams',
    localized_name: 'Vlaams',
    rtl: false,
  },
  sv_FI: {
    code: 'sv_FI',
    name: 'Swedish (Finland)',
    localized_name: 'Svenska (Finland)',
    rtl: false,
  },
  fr_CH: {
    code: 'fr_CH',
    name: 'French (Switzerland)',
    localized_name: 'Français (Suisse)',
    rtl: false,
  },
  'zh_CN.GB2312': {
    code: 'zh_CN.GB2312',
    name: 'Chinese (China) (GB2312)',
    localized_name: '中文 (中国)',
    rtl: false,
  },
  'zh_TW.Big5': {
    code: 'zh_TW.Big5',
    name: 'Chinese (Taiwan) (Big5) ',
    localized_name: '中文 (台灣)',
    rtl: false,
  },
  aln: {
    code: 'aln',
    name: 'Albanian Gheg',
    localized_name: 'Albanian Gheg',
    rtl: false,
  },
  tlh: {
    code: 'tlh',
    name: 'Klingon',
    localized_name: 'Klingon',
    rtl: false,
  },
  sw_KE: {
    code: 'sw_KE',
    name: 'Swahili (Kenya)',
    localized_name: 'Kiswahili',
    rtl: false,
  },
  kk_KZ: {
    code: 'kk_KZ',
    name: 'Kazakh (Kazakhstan)',
    localized_name: 'Kazakh (Kazakhstan)',
    rtl: false,
  },
  sn: {
    code: 'sn',
    name: 'Shona',
    localized_name: 'Shona',
    rtl: false,
  },
  ar_AA: {
    code: 'ar_AA',
    name: 'Arabic (Unitag)',
    localized_name: 'العربية',
    rtl: true,
  },
  brx: {
    code: 'brx',
    name: 'Bodo',
    localized_name: 'Bodo',
    rtl: false,
  },
  ny: {
    code: 'ny',
    name: 'Nyanja',
    localized_name: 'Nyanja',
    rtl: false,
  },
  sd: {
    code: 'sd',
    name: 'Sindhi',
    localized_name: 'Sindhi',
    rtl: false,
  },
  ach: {
    code: 'ach',
    name: 'Acoli',
    localized_name: 'Acoli',
    rtl: false,
  },
  cgg: {
    code: 'cgg',
    name: 'Chiga',
    localized_name: 'Chiga',
    rtl: false,
  },
  ff: {
    code: 'ff',
    name: 'Fulah',
    localized_name: 'Fulah',
    rtl: false,
  },
  lg: {
    code: 'lg',
    name: 'Ganda',
    localized_name: 'Ganda',
    rtl: false,
  },
  co: {
    code: 'co',
    name: 'Corsican',
    localized_name: 'Corsican',
    rtl: false,
  },
  udm: {
    code: 'udm',
    name: 'Udmurt',
    localized_name: 'Udmurt',
    rtl: false,
  },
  kab: {
    code: 'kab',
    name: 'Kabyle',
    localized_name: 'Kabyle',
    rtl: false,
  },
  os: {
    code: 'os',
    name: 'Ossetic',
    localized_name: 'Ossetic',
    rtl: false,
  },
  es_419: {
    code: 'es_419',
    name: 'Spanish (Latin America)',
    localized_name: 'Spanish (Latin America)',
    rtl: false,
  },
  de_AT: {
    code: 'de_AT',
    name: 'German (Austria)',
    localized_name: 'Deutsch (Österreich)',
    rtl: false,
  },
  dv: {
    code: 'dv',
    name: 'Divehi',
    localized_name: 'Divehi',
    rtl: true,
  },
  'ru@petr1708': {
    code: 'ru@petr1708',
    name: 'Russian Petrine orthography',
    localized_name: 'Russian Petrine orthography',
    rtl: false,
  },
  'en@pirate': {
    code: 'en@pirate',
    name: 'Pirate English',
    localized_name: 'Pirate English',
    rtl: false,
  },
  tn: {
    code: 'tn',
    name: 'Tswana',
    localized_name: 'Tswana',
    rtl: false,
  },
  ss: {
    code: 'ss',
    name: 'Swati',
    localized_name: 'Swati',
    rtl: false,
  },
  ts: {
    code: 'ts',
    name: 'Tsonga',
    localized_name: 'Tsonga',
    rtl: false,
  },
  'en@lolcat': {
    code: 'en@lolcat',
    name: 'LOLCAT English',
    localized_name: 'LOLCAT English',
    rtl: false,
  },
  tet: {
    code: 'tet',
    name: 'Tetum (Tetun)',
    localized_name: 'Tetum (Tetun)',
    rtl: false,
  },
  sah: {
    code: 'sah',
    name: 'Sakha (Yakut)',
    localized_name: 'Sakha (Yakut)',
    rtl: false,
  },
  om: {
    code: 'om',
    name: 'Oromo',
    localized_name: 'Oromo',
    rtl: false,
  },
  vec: {
    code: 'vec',
    name: 'Venetian',
    localized_name: 'Venetian',
    rtl: false,
  },
  'ug@Latin': {
    code: 'ug@Latin',
    name: 'Uighur (Latin)',
    localized_name: 'Uighur (Latin)',
    rtl: false,
  },
  tzm: {
    code: 'tzm',
    name: 'Central Atlas Tamazight',
    localized_name: 'Central Atlas Tamazight',
    rtl: false,
  },
  ady: {
    code: 'ady',
    name: 'Adyghe',
    localized_name: 'Adyghe',
    rtl: false,
  },
  cv: {
    code: 'cv',
    name: 'Chuvash',
    localized_name: 'Chuvash',
    rtl: false,
  },
  myv: {
    code: 'myv',
    name: 'Erzya',
    localized_name: 'Erzya',
    rtl: false,
  },
  lij: {
    code: 'lij',
    name: 'Ligurian',
    localized_name: 'Ligurian',
    rtl: false,
  },
  nia: {
    code: 'nia',
    name: 'Nias',
    localized_name: 'Nias',
    rtl: false,
  },
  mw1: {
    code: 'mw1',
    name: 'Mirandese',
    localized_name: 'Mirandese',
    rtl: false,
  },
  pfl: {
    code: 'pfl',
    name: 'Palatinate German',
    localized_name: 'Palatinate German',
    rtl: false,
  },
  gan: {
    code: 'gan',
    name: 'Chinese (Gan)',
    localized_name: 'Chinese (Gan)',
    rtl: false,
  },
  hak: {
    code: 'hak',
    name: 'Chinese (Hakka)',
    localized_name: 'Chinese (Hakka)',
    rtl: false,
  },
  czh: {
    code: 'czh',
    name: 'Chinese (Huizhou)',
    localized_name: 'Chinese (Huizhou)',
    rtl: false,
  },
  cjy: {
    code: 'cjy',
    name: 'Chinese (Jinyu)',
    localized_name: 'Chinese (Jinyu)',
    rtl: false,
  },
  lzh: {
    code: 'lzh',
    name: 'Chinese (Literary)',
    localized_name: 'Chinese (Literary)',
    rtl: false,
  },
  cmn: {
    code: 'cmn',
    name: 'Chinese (Mandarin)',
    localized_name: 'Chinese (Mandarin)',
    rtl: false,
  },
  mnp: {
    code: 'mnp',
    name: 'Chinese (Min Bei)',
    localized_name: 'Chinese (Min Bei)',
    rtl: false,
  },
  cdo: {
    code: 'cdo',
    name: 'Chinese (Min Dong)',
    localized_name: 'Chinese (Min Dong)',
    rtl: false,
  },
  nan: {
    code: 'nan',
    name: 'Chinese (Min Nan)',
    localized_name: 'Chinese (Min Nan)',
    rtl: false,
  },
  czo: {
    code: 'czo',
    name: 'Chinese (Min Zhong)',
    localized_name: 'Chinese (Min Zhong)',
    rtl: false,
  },
  cpx: {
    code: 'cpx',
    name: 'Chinese (Pu-Xian)',
    localized_name: 'Chinese (Pu-Xian)',
    rtl: false,
  },
  wuu: {
    code: 'wuu',
    name: 'Chinese (Wu)',
    localized_name: 'Chinese (Wu)',
    rtl: false,
  },
  hsn: {
    code: 'hsn',
    name: 'Chinese (Xiang)',
    localized_name: 'Chinese (Xiang)',
    rtl: false,
  },
  yue: {
    code: 'yue',
    name: 'Chinese (Yue)',
    localized_name: 'Chinese (Yue)',
    rtl: false,
  },
  pam: {
    code: 'pam',
    name: 'Kapampangan',
    localized_name: 'Kapampangan',
    rtl: false,
  },
  war: {
    code: 'war',
    name: 'Wáray-Wáray',
    localized_name: 'Wáray-Wáray',
    rtl: false,
  },
  szl: {
    code: 'szl',
    name: 'Silesian',
    localized_name: 'Silesian',
    rtl: false,
  },
  sma: {
    code: 'sma',
    name: 'Southern Sami',
    localized_name: 'Southern Sami',
    rtl: false,
  },
  tk_TM: {
    code: 'tk_TM',
    name: 'Turkmen (Turkmenistan)',
    localized_name: 'Turkmen (Turkmenistan)',
    rtl: false,
  },
  ar_EG: {
    code: 'ar_EG',
    name: 'Arabic (Egypt)',
    localized_name: 'العربية (مصر)',
    rtl: true,
  },
  ar_SY: {
    code: 'ar_SY',
    name: 'Arabic (Syria)',
    localized_name: 'العربية (سوريا)',
    rtl: true,
  },
  ff_SN: {
    code: 'ff_SN',
    name: 'Fulah (Senegal)',
    localized_name: 'Fulah (Senegal)',
    rtl: false,
  },
  nqo: {
    code: 'nqo',
    name: "N'ko",
    localized_name: "N'ko",
    rtl: true,
  },
  es_US: {
    code: 'es_US',
    name: 'Spanish (United States)',
    localized_name: 'Español (US)',
    rtl: false,
  },
  ksh: {
    code: 'ksh',
    name: 'Colognian',
    localized_name: 'Colognian',
    rtl: false,
  },
  dsb: {
    code: 'dsb',
    name: 'Lower Sorbian',
    localized_name: 'Lower Sorbian',
    rtl: false,
  },
  io: {
    code: 'io',
    name: 'Ido',
    localized_name: 'Ido',
    rtl: false,
  },
  scn: {
    code: 'scn',
    name: 'Sicilian',
    localized_name: 'Sicilian',
    rtl: false,
  },
  ru_ee: {
    code: 'ru_ee',
    name: 'Russian (Estonia)',
    localized_name: 'Русский (Estonia)',
    rtl: false,
  },
  en_ee: {
    code: 'en_ee',
    name: 'English (Estonia)',
    localized_name: 'English (Estonia)',
    rtl: false,
  },
  ru_lv: {
    code: 'ru_lv',
    name: 'Russian (Latvia)',
    localized_name: 'Русский (Latvia)',
    rtl: false,
  },
  en_lv: {
    code: 'en_lv',
    name: 'English (Latvia)',
    localized_name: 'English (Latvia)',
    rtl: false,
  },
  en_lt: {
    code: 'en_lt',
    name: 'English (Lithuania)',
    localized_name: 'English (Lithuania)',
    rtl: false,
  },
  ru_lt: {
    code: 'ru_lt',
    name: 'Russian (Lithuania)',
    localized_name: 'Русский (Lithuania)',
    rtl: false,
  },
  lmo: {
    code: 'lmo',
    name: 'Lombard',
    localized_name: 'Lombard',
    rtl: false,
  },
  vmf: {
    code: 'vmf',
    name: 'Upper Franconian',
    localized_name: 'Upper Franconian',
    rtl: false,
  },
  ba: {
    code: 'ba',
    name: 'Bashkir',
    localized_name: 'Bashkir',
    rtl: false,
  },
  en_NZ: {
    code: 'en_NZ',
    name: 'English (New Zealand)',
    localized_name: 'English (New Zealand)',
    rtl: false,
  },
  kl: {
    code: 'kl',
    name: 'Greenlandic',
    localized_name: 'Greenlandic',
    rtl: false,
  },
  'uz@Arab': {
    code: 'uz@Arab',
    name: 'Uzbek (Arabic)',
    localized_name: 'Uzbek (Arabic)',
    rtl: false,
  },
  'uz@Cyrl': {
    code: 'uz@Cyrl',
    name: 'Uzbek (Cyrillic)',
    localized_name: 'Uzbek (Cyrillic)',
    rtl: false,
  },
  'uz@Latn': {
    code: 'uz@Latn',
    name: 'Uzbek (Latin)',
    localized_name: 'Uzbek (Latin)',
    rtl: false,
  },
  ltg: {
    code: 'ltg',
    name: 'Latgalian',
    localized_name: 'Latgalian',
    rtl: false,
  },
  en_HK: {
    code: 'en_HK',
    name: 'English (Hong Kong)',
    localized_name: 'English (Hong Kong)',
    rtl: false,
  },
  en_SE: {
    code: 'en_SE',
    name: 'English (Sweden)',
    localized_name: 'English (Sweden)',
    rtl: false,
  },
  ast_ES: {
    code: 'ast_ES',
    name: 'Asturian (Spain)',
    localized_name: 'Asturian (Spain)',
    rtl: false,
  },
  jbo: {
    code: 'jbo',
    name: 'Lojban',
    localized_name: 'Lojban',
    rtl: false,
  },
  ar_SD: {
    code: 'ar_SD',
    name: 'Arabic (Sudan)',
    localized_name: 'العربية (السودان)',
    rtl: true,
  },
  'sr@Ijekavian': {
    code: 'sr@Ijekavian',
    name: 'Serbian (Ijekavian)',
    localized_name: 'Српски (Ijekavian)',
    rtl: false,
  },
  fr_BE: {
    code: 'fr_BE',
    name: 'French (Belgium)',
    localized_name: 'Français (Belgique)',
    rtl: false,
  },
  'az@latin': {
    code: 'az@latin',
    name: 'Azerbaijani (Latin)',
    localized_name: 'Azerbaijani (Latin)',
    rtl: false,
  },
  'ug@Cyrl': {
    code: 'ug@Cyrl',
    name: 'Uighur (Cyrillic)',
    localized_name: 'Uighur (Cyrillic)',
    rtl: false,
  },
  'ug@Arab': {
    code: 'ug@Arab',
    name: 'Uighur (Arabic)',
    localized_name: 'Uighur (Arabic)',
    rtl: false,
  },
  'kk@Cyrl': {
    code: 'kk@Cyrl',
    name: 'Kazakh (Cyrillic)',
    localized_name: 'Kazakh (Cyrillic)',
    rtl: false,
  },
  'kk@Arab': {
    code: 'kk@Arab',
    name: 'Kazakh (Arabic)',
    localized_name: 'Kazakh (Arabic)',
    rtl: false,
  },
  'kk@latin': {
    code: 'kk@latin',
    name: 'Kazakh (Latin)',
    localized_name: 'Kazakh (Latin)',
    rtl: false,
  },
  'sr@ijekavianlatin': {
    code: 'sr@ijekavianlatin',
    name: 'Serbian (Ijekavian Latin)',
    localized_name: 'Српски (Ijekavian Latin)',
    rtl: false,
  },
  nv: {
    code: 'nv',
    name: 'Navajo',
    localized_name: 'Navajo',
    rtl: false,
  },
  lez: {
    code: 'lez',
    name: 'Lezghian',
    localized_name: 'Lezghian',
    rtl: false,
  },
  lad: {
    code: 'lad',
    name: 'Ladino',
    localized_name: 'Ladino',
    rtl: false,
  },
  en_PL: {
    code: 'en_PL',
    name: 'English (Poland)',
    localized_name: 'English (Poland)',
    rtl: false,
  },
  en_CZ: {
    code: 'en_CZ',
    name: 'English (Czech Republic)',
    localized_name: 'English (Czech Republic)',
    rtl: false,
  },
  en_BE: {
    code: 'en_BE',
    name: 'English (Belgium)',
    localized_name: 'English (Belgium)',
    rtl: false,
  },
  en_CL: {
    code: 'en_CL',
    name: 'English (Chile)',
    localized_name: 'English (Chile)',
    rtl: false,
  },
  en_NL: {
    code: 'en_NL',
    name: 'English (Netherlands)',
    localized_name: 'English (Netherlands)',
    rtl: false,
  },
  en_DE: {
    code: 'en_DE',
    name: 'English (Germany)',
    localized_name: 'English (Germany)',
    rtl: false,
  },
  en_AT: {
    code: 'en_AT',
    name: 'English (Austria)',
    localized_name: 'English (Austria)',
    rtl: false,
  },
  en_RO: {
    code: 'en_RO',
    name: 'English (Romania)',
    localized_name: 'English (Romania)',
    rtl: false,
  },
  en_HU: {
    code: 'en_HU',
    name: 'English (Hungary)',
    localized_name: 'English (Hungary)',
    rtl: false,
  },
  en_CH: {
    code: 'en_CH',
    name: 'English (Switzerland)',
    localized_name: 'English (Switzerland)',
    rtl: false,
  },
  bar: {
    code: 'bar',
    name: 'Bavarian',
    localized_name: 'Bavarian',
    rtl: false,
  },
  haw: {
    code: 'haw',
    name: 'Hawaiian',
    localized_name: 'Hawaiian',
    rtl: false,
  },
  'az@Arab': {
    code: 'az@Arab',
    name: 'Azerbaijani (Arabic)',
    localized_name: 'Azerbaijani (Arabic)',
    rtl: false,
  },
  az_IR: {
    code: 'az_IR',
    name: 'Azerbaijani (Iran)',
    localized_name: 'Azerbaijani (Iran)',
    rtl: false,
  },
  en_FI: {
    code: 'en_FI',
    name: 'English (Finland)',
    localized_name: 'English (Finland)',
    rtl: false,
  },
  it_CH: {
    code: 'it_CH',
    name: 'Italian (Switzerland)',
    localized_name: 'Italiano (Svizzera)',
    rtl: false,
  },
  en_IN: {
    code: 'en_IN',
    name: 'English (India)',
    localized_name: 'English (India)',
    rtl: false,
  },
  en_GH: {
    code: 'en_GH',
    name: 'English (Ghana)',
    localized_name: 'English (Ghana)',
    rtl: false,
  },
  en_LK: {
    code: 'en_LK',
    name: 'English (Sri Lanka)',
    localized_name: 'English (Sri Lanka)',
    rtl: false,
  },
  en_BD: {
    code: 'en_BD',
    name: 'English (Bangladesh)',
    localized_name: 'English (Bangladesh)',
    rtl: false,
  },
  en_PK: {
    code: 'en_PK',
    name: 'English (Pakistan)',
    localized_name: 'English (Pakistan)',
    rtl: false,
  },
  'zh-Hans': {
    code: 'zh-Hans',
    name: 'Chinese Simplified',
    localized_name: '简体中文',
    rtl: false,
  },
  'zh-Hant': {
    code: 'zh-Hant',
    name: 'Chinese Traditional',
    localized_name: '繁體中文',
    rtl: false,
  },
  tzl: {
    code: 'tzl',
    name: 'Talossan',
    localized_name: 'Talossan',
    rtl: false,
  },
  en_NG: {
    code: 'en_NG',
    name: 'English (Nigeria)',
    localized_name: 'English (Nigeria)',
    rtl: false,
  },
  mh: {
    code: 'mh',
    name: 'Marshallese',
    localized_name: 'Marshallese',
    rtl: false,
  },
  iu: {
    code: 'iu',
    name: 'Inuktitut',
    localized_name: 'Inuktitut',
    rtl: false,
  },
  en_SK: {
    code: 'en_SK',
    name: 'English (Slovakia)',
    localized_name: 'English (Slovakia)',
    rtl: false,
  },
  es_GT: {
    code: 'es_GT',
    name: 'Spanish (Guatemala)',
    localized_name: 'Spanish (Guatemala)',
    rtl: false,
  },
  doi: {
    code: 'doi',
    name: 'Dogri',
    localized_name: 'Dogri',
    rtl: false,
  },
  kok: {
    code: 'kok',
    name: 'Konkani',
    localized_name: 'Konkani',
    rtl: false,
  },
  mni: {
    code: 'mni',
    name: 'Manipuri',
    localized_name: 'Manipuri',
    rtl: false,
  },
  sa: {
    code: 'sa',
    name: 'Sanskrit',
    localized_name: 'Sanskrit',
    rtl: false,
  },
  sat: {
    code: 'sat',
    name: 'Santali',
    localized_name: 'Santali',
    rtl: false,
  },
  uz_UZ: {
    code: 'uz_UZ',
    name: 'Uzbek (Uzbekistan)',
    localized_name: 'Uzbek (Uzbekistan)',
    rtl: false,
  },
  fa_AF: {
    code: 'fa_AF',
    name: 'Persian (Afghanistan)',
    localized_name: 'Persian (Afghanistan)',
    rtl: true,
  },
  ceb: {
    code: 'ceb',
    name: 'Cebuano',
    localized_name: 'Cebuano',
    rtl: false,
  },
  en_IT: {
    code: 'en_IT',
    name: 'English (Italy)',
    localized_name: 'English (Italy)',
    rtl: false,
  },
  en_ES: {
    code: 'en_ES',
    name: 'English (Spain)',
    localized_name: 'English (Spain)',
    rtl: false,
  },
  hu_RO: {
    code: 'hu_RO',
    name: 'Hungarian (Romanian)',
    localized_name: 'Hungarian (Romanian)',
    rtl: false,
  },
  es_HN: {
    code: 'es_HN',
    name: 'Spanish (Honduras)',
    localized_name: 'Spanish (Honduras)',
    rtl: false,
  },
  en_PT: {
    code: 'en_PT',
    name: 'English (Portugal)',
    localized_name: 'English (Portugal)',
    rtl: false,
  },
  en_GR: {
    code: 'en_GR',
    name: 'English (Greece)',
    localized_name: 'English (Greece)',
    rtl: false,
  },
  sg: {
    code: 'sg',
    name: 'Sango',
    localized_name: 'yângâ tî sängö',
    rtl: false,
  },
  en_NO: {
    code: 'en_NO',
    name: 'English (Norway)',
    localized_name: 'English (Norway)',
    rtl: false,
  },
  sw_CD: {
    code: 'sw_CD',
    name: 'Swahili (Democratic Republic of the Congo)',
    localized_name: 'Swahili (Democratic Republic of the Congo)',
    rtl: false,
  },
  en_HR: {
    code: 'en_HR',
    name: 'English (Croatia)',
    localized_name: 'English (Croatia)',
    rtl: false,
  },
  en_EG: {
    code: 'en_EG',
    name: 'English (Egypt)',
    localized_name: 'English (Egypt)',
    rtl: false,
  },
  nd: {
    code: 'nd',
    name: 'Ndebele, North',
    localized_name: 'Ndebele, North',
    rtl: false,
  },
  ro_MD: {
    code: 'ro_MD',
    name: 'Romanian (Moldova)',
    localized_name: 'Romanian (Moldova)',
    rtl: false,
  },
  en_MY: {
    code: 'en_MY',
    name: 'English (Malaysia)',
    localized_name: 'English (Malaysia)',
    rtl: false,
  },
  ar_AE: {
    code: 'ar_AE',
    name: 'Arabic (U.A.E.)',
    localized_name: 'Arabic (U.A.E.)',
    rtl: false,
  },
  ar_DZ: {
    code: 'ar_DZ',
    name: 'Arabic (Algeria)',
    localized_name: 'Arabic (Algeria)',
    rtl: false,
  },
  krl: {
    code: 'krl',
    name: 'Karelian',
    localized_name: 'Karelian',
    rtl: false,
  },
  vep: {
    code: 'vep',
    name: 'Vepsian',
    localized_name: 'Vepsian',
    rtl: false,
  },
  el_CY: {
    code: 'el_CY',
    name: 'Greek (Cyprus)',
    localized_name: 'Greek (Cyprus)',
    rtl: false,
  },
  en_CY: {
    code: 'en_CY',
    name: 'English (Cyprus)',
    localized_name: 'English (Cyprus)',
    rtl: false,
  },
  tr_CY: {
    code: 'tr_CY',
    name: 'Turkish (Cyprus)',
    localized_name: 'Turkish (Cyprus)',
    rtl: false,
  },
  'sr_ME@latin': {
    code: 'sr_ME@latin',
    name: 'Serbian (Latin) (Montenegro)',
    localized_name: 'Serbian (Latin) (Montenegro)',
    rtl: false,
  },
  'sr@Cyrl': {
    code: 'sr@Cyrl',
    name: 'Serbian (Cyrillic)',
    localized_name: 'Serbian (Cyrillic)',
    rtl: false,
  },
  sr_ME: {
    code: 'sr_ME',
    name: 'Serbian (Montenegro)',
    localized_name: 'Serbian (Montenegro)',
    rtl: false,
  },
  kbd: {
    code: 'kbd',
    name: 'Kabardian',
    localized_name: 'Kabardian',
    rtl: false,
  },
  ckb: {
    code: 'ckb',
    name: 'Central Kurdish',
    localized_name: 'Central Kurdish',
    rtl: true,
  },
  chr: {
    code: 'chr',
    name: 'Cherokee',
    localized_name: 'Cherokee',
    rtl: false,
  },
  'ja-Hira': {
    code: 'ja-Hira',
    name: 'Japanese (Hiragana)',
    localized_name: 'Japanese (Hiragana)',
    rtl: false,
  },
  fil_PH: {
    code: 'fil_PH',
    name: 'Filipino (Philippines)',
    localized_name: 'Filipino (Philippines)',
    rtl: false,
  },
  ab: {
    code: 'ab',
    name: 'Abkhaz',
    localized_name: 'Abkhaz',
    rtl: false,
  },
  br_FR: {
    code: 'br_FR',
    name: 'Breton (France)',
    localized_name: 'Breton (France)',
    rtl: false,
  },
  'ky@Arab': {
    code: 'ky@Arab',
    name: 'Kyrgyz (Arabic)',
    localized_name: 'Kyrgyz (Arabic)',
    rtl: false,
  },
  tsi: {
    code: 'tsi',
    name: 'Tsimshian',
    localized_name: 'Tsimshian',
    rtl: false,
  },
  lkt: {
    code: 'lkt',
    name: 'Lakota',
    localized_name: 'Lakota',
    rtl: false,
  },
  vo: {
    code: 'vo',
    name: 'Volapük',
    localized_name: 'Volapük',
    rtl: false,
  },
  ar_LB: {
    code: 'ar_LB',
    name: 'Arabic (Lebanon)',
    localized_name: 'Arabic (Lebanon)',
    rtl: false,
  },
  ar_JO: {
    code: 'ar_JO',
    name: 'Arabic (Jordan)',
    localized_name: 'Arabic (Jordan)',
    rtl: false,
  },
  en_DK: {
    code: 'en_DK',
    name: 'English (Denmark)',
    localized_name: 'English (Denmark)',
    rtl: false,
  },
  en_AE: {
    code: 'en_AE',
    name: 'English (United Arab Emirates)',
    localized_name: 'English (United Arab Emirates)',
    rtl: false,
  },
  ru_UA: {
    code: 'ru_UA',
    name: 'Russian (Ukraine)',
    localized_name: 'Russian (Ukraine)',
    rtl: false,
  },
  'sr_BA@latin': {
    code: 'sr_BA@latin',
    name: 'Serbian (Latin) (Bosnia and Herzegovina)',
    localized_name: 'Serbian (Latin) (Bosnia and Herzegovina)',
    rtl: false,
  },
  quh: {
    code: 'quh',
    name: 'South Bolivian Quechua',
    localized_name: 'South Bolivian Quechua',
    rtl: false,
  },
  aa_DJ: {
    code: 'aa_DJ',
    name: 'Afar (Djibouti)',
    localized_name: 'Afar (Djibouti)',
    rtl: false,
  },
  cak: {
    code: 'cak',
    name: 'Kaqchikel',
    localized_name: 'Kaqchikel',
    rtl: false,
  },
  tzj: {
    code: 'tzj',
    name: 'Tz’utujil',
    localized_name: 'Tz’utujil',
    rtl: false,
  },
  quc: {
    code: 'quc',
    name: "K'iche'",
    localized_name: "K'iche'",
    rtl: false,
  },
  bem_ZM: {
    code: 'bem_ZM',
    name: 'Bemba (Zambia)',
    localized_name: 'Bemba (Zambia)',
    rtl: false,
  },
  en_ZM: {
    code: 'en_ZM',
    name: 'English (Zambia)',
    localized_name: 'English (Zambia)',
    rtl: false,
  },
  en_PH: {
    code: 'en_PH',
    name: 'English (Philippines)',
    localized_name: 'English (Philippines)',
    rtl: false,
  },
  sw_TZ: {
    code: 'sw_TZ',
    name: 'Swahili (Tanzania)',
    localized_name: 'Swahili (Tanzania)',
    rtl: false,
  },
  sw_UG: {
    code: 'sw_UG',
    name: 'Swahili (Uganda)',
    localized_name: 'Swahili (Uganda)',
    rtl: false,
  },
  gug_PY: {
    code: 'gug_PY',
    name: 'Guarani (Paraguay)',
    localized_name: 'Guarani (Paraguay)',
    rtl: false,
  },
  loz_ZM: {
    code: 'loz_ZM',
    name: 'Lozi (Zambia)',
    localized_name: 'Lozi (Zambia)',
    rtl: false,
  },
  lg_UG: {
    code: 'lg_UG',
    name: 'Ganda (Uganda)',
    localized_name: 'Ganda (Uganda)',
    rtl: false,
  },
  bem: {
    code: 'bem',
    name: 'Bemba',
    localized_name: 'Bemba',
    rtl: false,
  },
  en_UG: {
    code: 'en_UG',
    name: 'English (Uganda)',
    localized_name: 'English (Uganda)',
    rtl: false,
  },
  qu: {
    code: 'qu',
    name: 'Quechua',
    localized_name: 'Quechua',
    rtl: false,
  },
  pt_MZ: {
    code: 'pt_MZ',
    name: 'Portuguese (Mozambique)',
    localized_name: 'Portuguese (Mozambique)',
    rtl: false,
  },
  fr_CI: {
    code: 'fr_CI',
    name: "French (Côte d'Ivoire)",
    localized_name: "French (Côte d'Ivoire)",
    rtl: false,
  },
  fr_GA: {
    code: 'fr_GA',
    name: 'French (Gabon)',
    localized_name: 'French (Gabon)',
    rtl: false,
  },
  fr_CM: {
    code: 'fr_CM',
    name: 'French (Cameroon)',
    localized_name: 'French (Cameroon)',
    rtl: false,
  },
  lue: {
    code: 'lue',
    name: 'Luvale',
    localized_name: 'Luvale',
    rtl: false,
  },
  kqn: {
    code: 'kqn',
    name: 'Kaonde',
    localized_name: 'Kaonde',
    rtl: false,
  },
  tpi: {
    code: 'tpi',
    name: 'Tok Pisin',
    localized_name: 'Tok Pisin',
    rtl: false,
  },
  ayl: {
    code: 'ayl',
    name: 'Libyan Arabic',
    localized_name: 'Libyan Arabic',
    rtl: false,
  },
  en_SG: {
    code: 'en_SG',
    name: 'English (Singapore)',
    localized_name: 'English (Singapore)',
    rtl: false,
  },
  zh_SG: {
    code: 'zh_SG',
    name: 'Chinese (Singapore)',
    localized_name: 'Chinese (Singapore)',
    rtl: false,
  },
  en_PR: {
    code: 'en_PR',
    name: 'English (Puerto Rico)',
    localized_name: 'English (Puerto Rico)',
    rtl: false,
  },
  el_DE: {
    code: 'el_DE',
    name: 'Greek (Germany)',
    localized_name: 'Greek (Germany)',
    rtl: false,
  },
  ms_BN: {
    code: 'ms_BN',
    name: 'Malay (Brunei)',
    localized_name: 'Malay (Brunei)',
    rtl: false,
  },
  'ms@Arab': {
    code: 'ms@Arab',
    name: 'Malay (Arabic)',
    localized_name: 'Malay (Arabic)',
    rtl: false,
  },
  'en@ysv': {
    code: 'en@ysv',
    name: 'Yeshivish English',
    localized_name: 'Yeshivish English',
    rtl: false,
  },
  en_AL: {
    code: 'en_AL',
    name: 'English (Albania)',
    localized_name: 'English (Albania)',
    rtl: false,
  },
  lus: {
    code: 'lus',
    name: 'Mizo',
    localized_name: 'Mizo',
    rtl: false,
  },
  grt: {
    code: 'grt',
    name: 'Garo',
    localized_name: 'Garo',
    rtl: false,
  },
  kha: {
    code: 'kha',
    name: 'Khasi',
    localized_name: 'Khasi',
    rtl: false,
  },
  hye: {
    code: 'hye',
    name: 'Eastern Armenian',
    localized_name: 'Eastern Armenian',
    rtl: false,
  },
  en_TT: {
    code: 'en_TT',
    name: 'English (Trinidad & Tobago)',
    localized_name: 'English (Trinidad & Tobago)',
    rtl: false,
  },
  qu_EC: {
    code: 'qu_EC',
    name: 'Quechua (Ecuador)',
    localized_name: 'Quechua (Ecuador)',
    rtl: false,
  },
  ay: {
    code: 'ay',
    name: 'Aymara',
    localized_name: 'Aymara',
    rtl: false,
  },
  bcq: {
    code: 'bcq',
    name: 'Bench',
    localized_name: 'Bench',
    rtl: false,
  },
  twd: {
    code: 'twd',
    name: 'Tweants',
    localized_name: 'Tweants',
    rtl: false,
  },
  tr_DE: {
    code: 'tr_DE',
    name: 'Turkish (Germany)',
    localized_name: 'Turkish (Germany)',
    rtl: false,
  },
  es_SA: {
    code: 'es_SA',
    name: 'Spanish (Saudi Arabia)',
    localized_name: 'Spanish (Saudi Arabia)',
    rtl: false,
  },
  ch: {
    code: 'ch',
    name: 'Chamorro',
    localized_name: 'Chamorro',
    rtl: false,
  },
  ki: {
    code: 'ki',
    name: 'Kikuyu',
    localized_name: 'Kikuyu',
    rtl: false,
  },
  ee: {
    code: 'ee',
    name: 'Ewe',
    localized_name: 'Ewe',
    rtl: false,
  },
  mhr: {
    code: 'mhr',
    name: 'Meadow Mari',
    localized_name: 'Meadow Mari',
    rtl: false,
  },
  mhr_RU: {
    code: 'mhr_RU',
    name: 'Eastern Mari (Russia)',
    localized_name: 'Eastern Mari (Russia)',
    rtl: false,
  },
  en_FR: {
    code: 'en_FR',
    name: 'English (France)',
    localized_name: 'English (France)',
    rtl: false,
  },
  en_BR: {
    code: 'en_BR',
    name: 'English (Brazil)',
    localized_name: 'English (Brazil)',
    rtl: false,
  },
  en_JP: {
    code: 'en_JP',
    name: 'English (Japan)',
    localized_name: 'English (Japan)',
    rtl: false,
  },
  xcl: {
    code: 'xcl',
    name: 'Classical Armenian',
    localized_name: 'Classical Armenian',
    rtl: false,
  },
  hye_RU: {
    code: 'hye_RU',
    name: 'Eastern Armenian (Russia)',
    localized_name: 'Eastern Armenian (Russia)',
    rtl: false,
  },
  hy_RU: {
    code: 'hy_RU',
    name: 'Armenian (Russia)',
    localized_name: 'Armenian (Russia)',
    rtl: false,
  },
  pa_PK: {
    code: 'pa_PK',
    name: 'Panjabi (Pakistan)',
    localized_name: 'Panjabi (Pakistan)',
    rtl: true,
  },
  rap: {
    code: 'rap',
    name: 'Rapa Nui',
    localized_name: 'Rapa Nui',
    rtl: false,
  },
  ps_AF: {
    code: 'ps_AF',
    name: 'Pushto (Afghanistan)',
    localized_name: 'Pushto (Afghanistan)',
    rtl: false,
  },
  ie: {
    code: 'ie',
    name: 'Interlingue',
    localized_name: 'Interlingue',
    rtl: false,
  },
  ar_IQ: {
    code: 'ar_IQ',
    name: 'Arabic (Iraq)',
    localized_name: 'Arabic (Iraq)',
    rtl: true,
  },
  arc: {
    code: 'arc',
    name: 'Aramaic',
    localized_name: 'Aramaic',
    rtl: false,
  },
  en_RS: {
    code: 'en_RS',
    name: 'English (Serbia)',
    localized_name: 'English (Serbia)',
    rtl: false,
  },
  en_BA: {
    code: 'en_BA',
    name: 'English (Bosnia and Herzegovina)',
    localized_name: 'English (Bosnia and Herzegovina)',
    rtl: false,
  },
  chk: {
    code: 'chk',
    name: 'Chuukese',
    localized_name: 'Chuukese',
    rtl: false,
  },
  es_CU: {
    code: 'es_CU',
    name: 'Spanish (Cuba)',
    localized_name: 'Spanish (Cuba)',
    rtl: false,
  },
  en_SI: {
    code: 'en_SI',
    name: 'English (Slovenia)',
    localized_name: 'English (Slovenia)',
    rtl: false,
  },
  'en_BA-SRP': {
    code: 'en_BA-SRP',
    name: 'English (Republika Srpska)',
    localized_name: 'English (Republika Srpska)',
    rtl: false,
  },
};

/**
 * Get language information
 *
 * @param {String} code
 * @returns {Object} Language details
 */
function getLanguageInfo(code) {
  return LANGUAGES[code] || {
    code,
    name: code,
    localized_name: code,
    rtl: false,
  };
}

module.exports = {
  getLanguageInfo,
};
